language: java
services:
  - mysql
  - docker
before_install:
  - mysql -e 'CREATE DATABASE Cyber; GRANT ALL PRIVILEGES ON Cyber.* TO "spring"@"localhost" IDENTIFIED BY "cyber"; FLUSH PRIVILEGES;'
script:
  - mvn install
  - docker-compose up --build -d
deploy:
  provider: script
  script: sh deploy.sh $word
  on:
    branch: master